---
- name: Deploy Docker Compose stack
  hosts: all
  become: true

  tasks:
    - name: Install Docker
      apt:
        name: docker.io
        state: present
        update_cache: yes

    - name: Install Docker Compose
      apt:
        name: docker-compose
        state: present

    - name: Cleanup existing Docker containers
      shell: |
        docker rm -f imagecapdb model-service imagecap-service imagecapapp || true

    - name: Cleanup existing Docker images
      shell: |
        docker rmi -f abhipsapanda/modelbe1 abhipsapanda/backend abhipsapanda/frontend || true

    - name: Pull Model Service Image
      docker_image:
        name: abhipsapanda/modelbe1
        source: pull

    - name: Pull Backend Image
      docker_image:
        name: abhipsapanda/backend
        source: pull

    - name: Pull Frontend Image
      docker_image:
        name: abhipsapanda/frontend
        source: pull

    - name: Copy Docker Compose file to host
      copy:
        src: /var/lib/jenkins/workspace/spedemo/docker-compose.yml
        dest: /opt/docker-compose.yml

    - name: Start Docker Compose stack
      command: docker-compose up -d
      args:
        chdir: /opt/
